export const countriesList = [
    { name: "Afghanistan", flag: "🇦🇫", link: "/afghanistan", short: "af" },
    { name: "Albania", flag: "🇦🇱", link: "/albania", short: "al" },
    { name: "Algeria", flag: "🇩🇿", link: "/algeria", short: "dz" },
    { name: "Andorra", flag: "🇦🇩", link: "/andorra", short: "ad" },
    { name: "Angola", flag: "🇦🇴", link: "/angola", short: "ao" },
    { name: "Antigua and Barbuda", flag: "🇦🇬", link: "/antigua-and-barbuda", short: "ag" },
    { name: "Argentina", flag: "🇦🇷", link: "/argentina", short: "ar" },
    { name: "Armenia", flag: "🇦🇲", link: "/armenia", short: "am" },
    { name: "Australia", flag: "🇦🇺", link: "/australia", short: "au" },
    { name: "Austria", flag: "🇦🇹", link: "/austria", short: "at" },
    { name: "Azerbaijan", flag: "🇦🇿", link: "/azerbaijan", short: "az" },
    { name: "Bahamas", flag: "🇧🇸", link: "/bahamas", short: "bs" },
    { name: "Bahrain", flag: "🇧🇭", link: "/bahrain", short: "bh" },
    { name: "Bangladesh", flag: "🇧🇩", link: "/bangladesh", short: "bd" },
    { name: "Barbados", flag: "🇧🇧", link: "/barbados", short: "bb" },
    { name: "Belarus", flag: "🇧🇾", link: "/belarus", short: "by" },
    { name: "Belgium", flag: "🇧🇪", link: "/belgium", short: "be" },
    { name: "Belize", flag: "🇧🇿", link: "/belize", short: "bz" },
    { name: "Benin", flag: "🇧🇯", link: "/benin", short: "bj" },
    { name: "Bhutan", flag: "🇧🇹", link: "/bhutan", short: "bt" },
    { name: "Bolivia", flag: "🇧🇴", link: "/bolivia", short: "bo" },
    { name: "Bosnia and Herzegovina", flag: "🇧🇦", link: "/bosnia-and-herzegovina", short: "ba" },
    { name: "Botswana", flag: "🇧🇼", link: "/botswana", short: "bw" },
    { name: "Brazil", flag: "🇧🇷", link: "/brazil", short: "br" },
    { name: "Brunei", flag: "🇧🇳", link: "/brunei", short: "bn" },
    { name: "Bulgaria", flag: "🇧🇬", link: "/bulgaria", short: "bg" },
    { name: "Burkina Faso", flag: "🇧🇫", link: "/burkina-faso", short: "bf" },
    { name: "Burundi", flag: "🇧🇮", link: "/burundi", short: "bi" },
    { name: "Cabo Verde", flag: "🇨🇻", link: "/cabo-verde", short: "cv" },
    { name: "Cambodia", flag: "🇰🇭", link: "/cambodia", short: "kh" },
    { name: "Cameroon", flag: "🇨🇲", link: "/cameroon", short: "cm" },
    { name: "Canada", flag: "🇨🇦", link: "/canada", short: "ca" },
    { name: "Central African Republic", flag: "🇨🇫", link: "/central-african-republic", short: "cf" },
    { name: "Chad", flag: "🇹🇩", link: "/chad", short: "td" },
    { name: "Chile", flag: "🇨🇱", link: "/chile", short: "cl" },
    { name: "China", flag: "🇨🇳", link: "/china", short: "cn" },
    { name: "Colombia", flag: "🇨🇴", link: "/colombia", short: "co" },
    { name: "Comoros", flag: "🇰🇲", link: "/comoros", short: "km" },
    { name: "Congo, Democratic Republic of the", flag: "🇨🇩", link: "/congo-democratic-republic-of-the", short: "cd" },
    { name: "Congo, Republic of the", flag: "🇨🇬", link: "/congo-republic-of-the", short: "cg" },
    { name: "Costa Rica", flag: "🇨🇷", link: "/costa-rica", short: "cr" },
    { name: "Croatia", flag: "🇭🇷", link: "/croatia", short: "hr" },
    { name: "Cuba", flag: "🇨🇺", link: "/cuba", short: "cu" },
    { name: "Cyprus", flag: "🇨🇾", link: "/cyprus", short: "cy" },
    { name: "Czech Republic", flag: "🇨🇿", link: "/czech-republic", short: "cz" },
    { name: "Denmark", flag: "🇩🇰", link: "/denmark", short: "dk" },
    { name: "Djibouti", flag: "🇩🇯", link: "/djibouti", short: "dj" },
    { name: "Dominica", flag: "🇩🇲", link: "/dominica", short: "dm" },
    { name: "Dominican Republic", flag: "🇩🇴", link: "/dominican-republic", short: "do" },
    { name: "Ecuador", flag: "🇪🇨", link: "/ecuador", short: "ec" },
    { name: "Egypt", flag: "🇪🇬", link: "/egypt", short: "eg" },
    { name: "El Salvador", flag: "🇸🇻", link: "/el-salvador", short: "sv" },
    { name: "Equatorial Guinea", flag: "🇬🇶", link: "/equatorial-guinea", short: "gq" },
    { name: "Eritrea", flag: "🇪🇷", link: "/eritrea", short: "er" },
    { name: "Estonia", flag: "🇪🇪", link: "/estonia", short: "ee" },
    { name: "Eswatini", flag: "🇸🇿", link: "/eswatini", short: "sz" },
    { name: "Ethiopia", flag: "🇪🇹", link: "/ethiopia", short: "et" },
    { name: "Fiji", flag: "🇫🇯", link: "/fiji", short: "fj" },
    { name: "Finland", flag: "🇫🇮", link: "/finland", short: "fi" },
    { name: "France", flag: "🇫🇷", link: "/france", short: "fr" },
    { name: "Gabon", flag: "🇬🇦", link: "/gabon", short: "ga" },
    { name: "Gambia", flag: "🇬🇲", link: "/gambia", short: "gm" },
    { name: "Georgia", flag: "🇬🇪", link: "/georgia", short: "ge" },
    { name: "Germany", flag: "🇩🇪", link: "/germany", short: "de" },
    { name: "Ghana", flag: "🇬🇭", link: "/ghana", short: "gh" },
    { name: "Greece", flag: "🇬🇷", link: "/greece", short: "gr" },
    { name: "Grenada", flag: "🇬🇩", link: "/grenada", short: "gd" },
    { name: "Guatemala", flag: "🇬🇹", link: "/guatemala", short: "gt" },
    { name: "Guinea", flag: "🇬🇳", link: "/guinea", short: "gn" },
    { name: "Guinea-Bissau", flag: "🇬🇼", link: "/guinea-bissau", short: "gw" },
    { name: "Guyana", flag: "🇬🇾", link: "/guyana", short: "gy" },
    { name: "Haiti", flag: "🇭🇹", link: "/haiti", short: "ht" },
    { name: "Honduras", flag: "🇭🇳", link: "/honduras", short: "hn" },
    { name: "Hungary", flag: "🇭🇺", link: "/hungary", short: "hu" },
    { name: "Iceland", flag: "🇮🇸", link: "/iceland", short: "is" },
    { name: "India", flag: "🇮🇳", link: "/india", short: "in" },
    { name: "Indonesia", flag: "🇮🇩", link: "/indonesia", short: "id" },
    { name: "Iran", flag: "🇮🇷", link: "/iran", short: "ir" },
    { name: "Iraq", flag: "🇮🇶", link: "/iraq", short: "iq" },
    { name: "Ireland", flag: "🇮🇪", link: "/ireland", short: "ie" },
    { name: "Israel", flag: "🇮🇱", link: "/israel", short: "il" },
    { name: "Italy", flag: "🇮🇹", link: "/italy", short: "it" },
    { name: "Jamaica", flag: "🇯🇲", link: "/jamaica", short: "jm" },
    { name: "Japan", flag: "🇯🇵", link: "/japan", short: "jp" },
    { name: "Jordan", flag: "🇯🇴", link: "/jordan", short: "jo" },
    { name: "Kazakhstan", flag: "🇰🇿", link: "/kazakhstan", short: "kz" },
    { name: "Kenya", flag: "🇰🇪", link: "/kenya", short: "ke" },
    { name: "Kiribati", flag: "🇰🇮", link: "/kiribati", short: "ki" },
    { name: "Korea, North", flag: "🇰🇵", link: "/korea-north", short: "kp" },
    { name: "Korea, South", flag: "🇰🇷", link: "/korea-south", short: "kr" },
    { name: "Kuwait", flag: "🇰🇼", link: "/kuwait", short: "kw" },
    { name: "Kyrgyzstan", flag: "🇰🇬", link: "/kyrgyzstan", short: "kg" },
    { name: "Laos", flag: "🇱🇦", link: "/laos", short: "la" },
    { name: "Latvia", flag: "🇱🇻", link: "/latvia", short: "lv" },
    { name: "Lebanon", flag: "🇱🇧", link: "/lebanon", short: "lb" },
    { name: "Lesotho", flag: "🇱🇸", link: "/lesotho", short: "ls" },
    { name: "Liberia", flag: "🇱🇷", link: "/liberia", short: "lr" },
    { name: "Libya", flag: "🇱🇾", link: "/libya", short: "ly" },
    { name: "Liechtenstein", flag: "🇱🇮", link: "/liechtenstein", short: "li" },
    { name: "Lithuania", flag: "🇱🇹", link: "/lithuania", short: "lt" },
    { name: "Luxembourg", flag: "🇱🇺", link: "/luxembourg", short: "lu" },
    { name: "Madagascar", flag: "🇲🇬", link: "/madagascar", short: "mg" },
    { name: "Malawi", flag: "🇲🇼", link: "/malawi", short: "mw" },
    { name: "Malaysia", flag: "🇲🇾", link: "/malaysia", short: "my" },
    { name: "Maldives", flag: "🇲🇻", link: "/maldives", short: "mv" },
    { name: "Mali", flag: "🇲🇱", link: "/mali", short: "ml" },
    { name: "Malta", flag: "🇲🇹", link: "/malta", short: "mt" },
    { name: "Marshall Islands", flag: "🇲🇭", link: "/marshall-islands", short: "mh" },
    { name: "Mauritania", flag: "🇲🇷", link: "/mauritania", short: "mr" },
    { name: "Mauritius", flag: "🇲🇺", link: "/mauritius", short: "mu" },
    { name: "Mexico", flag: "🇲🇽", link: "/mexico", short: "mx" },
    { name: "Micronesia", flag: "🇫🇲", link: "/micronesia", short: "fm" },
    { name: "Moldova", flag: "🇲🇩", link: "/moldova", short: "md" },
    { name: "Monaco", flag: "🇲🇨", link: "/monaco", short: "mc" },
    { name: "Mongolia", flag: "🇲🇳", link: "/mongolia", short: "mn" },
    { name: "Montenegro", flag: "🇲🇪", link: "/montenegro", short: "me" },
    { name: "Morocco", flag: "🇲🇦", link: "/morocco", short: "ma" },
    { name: "Mozambique", flag: "🇲🇿", link: "/mozambique", short: "mz" },
    { name: "Myanmar", flag: "🇲🇲", link: "/myanmar", short: "mm" },
    { name: "Namibia", flag: "🇳🇦", link: "/namibia", short: "na" },
    { name: "Nauru", flag: "🇳🇷", link: "/nauru", short: "nr" },
    { name: "Nepal", flag: "🇳🇵", link: "/nepal", short: "np" },
    { name: "Netherlands", flag: "🇳🇱", link: "/netherlands", short: "nl" },
    { name: "New Zealand", flag: "🇳🇿", link: "/new-zealand", short: "nz" },
    { name: "Nicaragua", flag: "🇳🇮", link: "/nicaragua", short: "ni" },
    { name: "Niger", flag: "🇳🇪", link: "/niger", short: "ne" },
    { name: "Nigeria", flag: "🇳🇬", link: "/nigeria", short: "ng" },
    { name: "North Macedonia", flag: "🇲🇰", link: "/north-macedonia", short: "mk" },
    { name: "Norway", flag: "🇳🇴", link: "/norway", short: "no" },
    { name: "Oman", flag: "🇴🇲", link: "/oman", short: "om" },
    { name: "Pakistan", flag: "🇵🇰", link: "/pakistan", short: "pk" },
    { name: "Palau", flag: "🇵🇼", link: "/palau", short: "pw" },
    { name: "Palestine", flag: "🇵🇸", link: "/palestine", short: "ps" },
    { name: "Panama", flag: "🇵🇦", link: "/panama", short: "pa" },
    { name: "Papua New Guinea", flag: "🇵🇬", link: "/papua-new-guinea", short: "pg" },
    { name: "Paraguay", flag: "🇵🇾", link: "/paraguay", short: "py" },
    { name: "Peru", flag: "🇵🇪", link: "/peru", short: "pe" },
    { name: "Philippines", flag: "🇵🇭", link: "/philippines", short: "ph" },
    { name: "Poland", flag: "🇵🇱", link: "/poland", short: "pl" },
    { name: "Portugal", flag: "🇵🇹", link: "/portugal", short: "pt" },
    { name: "Qatar", flag: "🇶🇦", link: "/qatar", short: "qa" },
    { name: "Romania", flag: "🇷🇴", link: "/romania", short: "ro" },
    { name: "Russia", flag: "🇷🇺", link: "/russia", short: "ru" },
    { name: "Rwanda", flag: "🇷🇼", link: "/rwanda", short: "rw" },
    { name: "Saint Kitts and Nevis", flag: "🇰🇳", link: "/saint-kitts-and-nevis", short: "kn" },
    { name: "Saint Lucia", flag: "🇱🇨", link: "/saint-lucia", short: "lc" },
    { name: "Saint Vincent and the Grenadines", flag: "🇻🇨", link: "/saint-vincent-and-the-grenadines", short: "vc" },
    { name: "Samoa", flag: "🇼🇸", link: "/samoa", short: "ws" },
    { name: "San Marino", flag: "🇸🇲", link: "/san-marino", short: "sm" },
    { name: "Sao Tome and Principe", flag: "🇸🇹", link: "/sao-tome-and-principe", short: "st" },
    { name: "Saudi Arabia", flag: "🇸🇦", link: "/saudi-arabia", short: "sa" },
    { name: "Senegal", flag: "🇸🇳", link: "/senegal", short: "sn" },
    { name: "Serbia", flag: "🇷🇸", link: "/serbia", short: "rs" },
    { name: "Seychelles", flag: "🇸🇨", link: "/seychelles", short: "sc" },
    { name: "Sierra Leone", flag: "🇸🇱", link: "/sierra-leone", short: "sl" },
    { name: "Singapore", flag: "🇸🇬", link: "/singapore", short: "sg" },
    { name: "Slovakia", flag: "🇸🇰", link: "/slovakia", short: "sk" },
    { name: "Slovenia", flag: "🇸🇮", link: "/slovenia", short: "si" },
    { name: "Solomon Islands", flag: "🇸🇧", link: "/solomon-islands", short: "sb" },
    { name: "Somalia", flag: "🇸🇴", link: "/somalia", short: "so" },
    { name: "South Africa", flag: "🇿🇦", link: "/south-africa", short: "za" },
    { name: "South Korea", flag: "🇰🇷", link: "/south-korea", short: "kr" },
    { name: "South Sudan", flag: "🇸🇸", link: "/south-sudan", short: "ss" },
    { name: "Spain", flag: "🇪🇸", link: "/spain", short: "es" },
    { name: "Sri Lanka", flag: "🇱🇰", link: "/sri-lanka", short: "lk" },
    { name: "Sudan", flag: "🇸🇩", link: "/sudan", short: "sd" },
    { name: "Suriname", flag: "🇸🇷", link: "/suriname", short: "sr" },
    { name: "Sweden", flag: "🇸🇪", link: "/sweden", short: "se" },
    { name: "Switzerland", flag: "🇨🇭", link: "/switzerland", short: "ch" },
    { name: "Syria", flag: "🇸🇾", link: "/syria", short: "sy" },
    { name: "Taiwan", flag: "🇹🇼", link: "/taiwan", short: "tw" },
    { name: "Tajikistan", flag: "🇹🇯", link: "/tajikistan", short: "tj" },
    { name: "Tanzania", flag: "🇹🇿", link: "/tanzania", short: "tz" },
    { name: "Thailand", flag: "🇹🇭", link: "/thailand", short: "th" },
    { name: "Timor-Leste", flag: "🇹🇱", link: "/timor-leste", short: "tl" },
    { name: "Togo", flag: "🇹🇬", link: "/togo", short: "tg" },
    { name: "Tonga", flag: "🇹🇴", link: "/tonga", short: "to" },
    { name: "Trinidad and Tobago", flag: "🇹🇹", link: "/trinidad-and-tobago", short: "tt" },
    { name: "Tunisia", flag: "🇹🇳", link: "/tunisia", short: "tn" },
    { name: "Turkey", flag: "🇹🇷", link: "/turkey", short: "tr" },
    { name: "Turkmenistan", flag: "🇹🇲", link: "/turkmenistan", short: "tm" },
    { name: "Tuvalu", flag: "🇹🇻", link: "/tuvalu", short: "tv" },
    { name: "Uganda", flag: "🇺🇬", link: "/uganda", short: "ug" },
    { name: "Ukraine", flag: "🇺🇦", link: "/ukraine", short: "ua" },
    { name: "United Arab Emirates", flag: "🇦🇪", link: "/united-arab-emirates", short: "ae" },
    { name: "United Kingdom", flag: "🇬🇧", link: "/united-kingdom", short: "gb" },
    { name: "United States", flag: "🇺🇸", link: "/united-states", short: "us" },
    { name: "Uruguay", flag: "🇺🇾", link: "/uruguay", short: "uy" },
    { name: "Uzbekistan", flag: "🇺🇿", link: "/uzbekistan", short: "uz" },
    { name: "Vanuatu", flag: "🇻🇺", link: "/vanuatu", short: "vu" },
    { name: "Vatican City", flag: "🇻🇦", link: "/vatican-city", short: "va" },
    { name: "Venezuela", flag: "🇻🇪", link: "/venezuela", short: "ve" },
    { name: "Vietnam", flag: "🇻🇳", link: "/vietnam", short: "vn" },
    { name: "Yemen", flag: "🇾🇪", link: "/yemen", short: "ye" },
    { name: "Zambia", flag: "🇿🇲", link: "/zambia", short: "zm" },
    { name: "Zimbabwe", flag: "🇿🇼", link: "/zimbabwe", short: "zw" }
]